apiVersion: v1
kind: Secret
metadata:
  name: ai-circo-secrets
  namespace: recycling
type: Opaque
stringData:
  # Database
  database-url: "postgresql://user:password@db-service:5432/recycling_db"
  
  # Security
  secret-key: "change-this-in-production"
  jwt-secret: "change-this-in-production"
  
  # Grafana
  grafana-admin-password: "change-this-in-production"

---
apiVersion: v1
kind: Secret
metadata:
  name: robot-certs
  namespace: recycling
type: Opaque
stringData:
  # Robot SSL certificates
  robot.crt: |
    -----BEGIN CERTIFICATE-----
    Replace with actual certificate
    -----END CERTIFICATE-----
  robot.key: |
    -----BEGIN PRIVATE KEY-----
    Replace with actual private key
    -----END PRIVATE KEY----- 