apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-circo-config
  namespace: recycling
data:
  # Vision System
  vision-model-path: "/app/models/plastic_yolo11.pt"
  vision-confidence-threshold: "0.85"
  
  # Robot Controller
  robot-ip: "192.168.1.100"
  robot-port: "8002"
  max-workers: "4"
  emergency-stop-timeout: "5"
  
  # API Configuration
  api-host: "0.0.0.0"
  api-port: "8000"
  debug: "false"
  
  # Redis Cache
  redis-url: "redis://redis-service:6379/0"
  
  # Monitoring
  prometheus-port: "9090"
  grafana-port: "3000"
  
  # Storage
  models-storage-path: "/app/models"
  cache-storage-path: "/app/cache"
  
  # Logging
  log-level: "INFO"
  log-format: "json" 