apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-circo-api
  namespace: recycling
  labels:
    app: ai-circo
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-circo
      component: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ai-circo
        component: api
    spec:
      containers:
      - name: api
        image: ai-circo/api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-circo-secrets
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ai-circo-secrets
              key: secret-key
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: ai-circo-config
              key: redis-url
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: models
          mountPath: /app/models
        - name: config
          mountPath: /app/config
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: ai-circo-models
      - name: config
        configMap:
          name: ai-circo-config 