apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-circo-vision
  namespace: recycling
  labels:
    app: ai-circo
    component: vision
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-circo
      component: vision
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ai-circo
        component: vision
    spec:
      containers:
      - name: vision
        image: ai-circo/vision:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "2000m"
            memory: "4Gi"
            nvidia.com/gpu: 1
        env:
        - name: MODEL_PATH
          value: "/app/models/plastic_yolo11.pt"
        - name: CONFIDENCE_THRESHOLD
          valueFrom:
            configMapKeyRef:
              name: ai-circo-config
              key: vision-confidence-threshold
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: models
          mountPath: /app/models
        - name: cache
          mountPath: /app/cache
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: ai-circo-models
      - name: cache
        emptyDir: {}
      nodeSelector:
        accelerator: nvidia-tesla 